modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT License"

issueTrackerURL = "https://github.com/Towdium/JustEnoughCharacters/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Towdium/JustEnoughCharacters"
credits = "Thanks to TartaricAcid, 3TUSK, Seraph_JACK, Snownee and many people for their efforts for development of the Chinese modding community."
authors = "Towdium, yzl210, Death-123, vfyjxf_"
description = "Pinyin search for JEI and more."



